version: 1.0.{build}
branches:
  only:
    - master
image: Visual Studio 2015
clone_depth: 50
platform: Any CPU
configuration: Debug
build:
   project: "travis-ci_sample/travis-ci_sample.sln"
   verbosity: normal
test: off
deploy: off
  - echo That's so easy!
